build.cmd, build.sh, samples/SessionSample/project.json, src/Microsoft.AspNet.Session/project.json, test/Microsoft.AspNet.Session.Tests/project.json
Prepping to be merged once ready.
=> Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

samples/SessionSample/project.json, src/Microsoft.AspNet.Session/DistributedSession.cs, src/Microsoft.AspNet.Session/DistributedSessionStore.cs, src/Microsoft.AspNet.Session/SessionMiddlewareExtensions.cs, src/Microsoft.AspNet.Session/project.json
Dependent on https://github.com/aspnet/Caching/pull/49/files
@muratg
=> React to Caching package rename

src/Microsoft.AspNet.Session/SessionDefaults.cs, src/Microsoft.AspNet.Session/SessionMiddleware.cs, src/Microsoft.AspNet.Session/SessionOptions.cs
Remove the duplication in SessionOptions, SessionMiddleware [Refactoring], by adding a "CookiePath" to the "SessionDefaults"
=> Adds CookiePath to SessionDefaults

build.cmd
@davidfowl @Eilon I made this PR based on the issue #18
=> Update 'dnvmx -x86' switch

samples/SessionSample/Startup.cs, test/Microsoft.AspNet.Session.Tests/SessionTests.cs
React to aspnet/HttpAbstractions#280
=> React to SessionCollectionExtensions renames

src/Microsoft.AspNet.Session/DistributedSession.cs, src/Microsoft.AspNet.Session/project.json
@Tratcher : As discussed these are temporary changes to enable Caching api review changes to be checked in. This will be revisited for Session api review changes.
=> Reacting to Caching api review changes

src/Microsoft.AspNet.Session/DistributedSession.cs, test/Microsoft.AspNet.Session.Tests/SessionTests.cs
=> [Fixes #41] Refresh the session even when its not accessed in current request

test/Microsoft.AspNet.Session.Tests/SessionTests.cs
@Tratcher just added some unit tests. I do not intend to check these into release.
=> Added unit tests

test/Microsoft.AspNet.Session.Tests/project.json
=> Enable Microsoft.AspNet.Session.Tests on CoreCLR.

samples/SessionSample/Startup.cs
Reacting to https://github.com/aspnet/Logging/pull/314.
Built sample locally.
=> Reacting to verbose rename

src/Microsoft.AspNet.Session/DistributedSession.cs, src/Microsoft.AspNet.Session/LoggingExtensions.cs, src/Microsoft.AspNet.Session/SessionMiddleware.cs
=> Adding logging event ids

samples/SessionSample/Startup.cs, samples/SessionSample/hosting.json, samples/SessionSample/project.json, samples/SessionSample/wwwroot/web.config, test/Microsoft.AspNet.Session.Tests/SessionTests.cs
Reacting to https://github.com/aspnet/Hosting/pull/521
=> Reacting to new Hosting API

.gitattributes, .gitignore, .travis.yml, appveyor.yml, build.cmd, build.sh, makefile.shade, test/Microsoft.AspNet.Session.Tests/project.json
=> Build with dotnet

NuGetPackageVerifier.json, src/Microsoft.AspNetCore.Session/project.json
=> Enabled xml doc generation

src/Microsoft.AspNetCore.Session/SessionDefaults.cs
=> Update cookie name

samples/SessionSample/Startup.cs, samples/SessionSample/project.json, samples/SessionSample/web.config, samples/SessionSample/wwwroot/Readme.md, samples/SessionSample/wwwroot/web.config
Moving web.config from wwwroot to application root.
=> Moving web.config

samples/SessionSample/project.json, samples/SessionSample/web.config
=> Update web.config and add publish tool

samples/SessionSample/Properties/launchSettings.json, samples/SessionSample/Startup.cs, samples/SessionSample/project.json, src/Microsoft.AspNetCore.Session/CookieProtection.cs, src/Microsoft.AspNetCore.Session/LoggingExtensions.cs, src/Microsoft.AspNetCore.Session/SessionMiddleware.cs, src/Microsoft.AspNetCore.Session/SessionServiceCollectionExtensions.cs, src/Microsoft.AspNetCore.Session/project.json, test/Microsoft.AspNetCore.Session.Tests/Microsoft.AspNetCore.Session.Tests.xproj
=> Use DataProtection to encrypt the cookie

samples/SessionSample/Startup.cs, samples/SessionSample/project.json
@Tratcher hope this fixes the issue #127
=> Update sample to include Redis for Core

src/Microsoft.AspNetCore.Session/DistributedSession.cs, src/Microsoft.AspNetCore.Session/DistributedSessionStore.cs, src/Microsoft.AspNetCore.Session/ISessionStore.cs, src/Microsoft.AspNetCore.Session/SessionMiddleware.cs, src/Microsoft.AspNetCore.Session/SessionOptions.cs, src/Microsoft.AspNetCore.Session/breakingchanges.netcore.json
#167 Depends on https://github.com/aspnet/HttpAbstractions/pull/879
=> Add cancellation tokens and defualt timeouts for Load/CommitAsync.

src/Microsoft.AspNetCore.Session/SessionOptions.cs
https://github.com/aspnet/Home/issues/2393
Documenting this decision for posterity.
=> Mark cookie as non-essential

test/Microsoft.AspNetCore.Session.Tests/SessionTests.cs
Preparing for aspnet/Logging#804
=> Update usage of TestSink

build/dependencies.props, samples/SessionSample/SessionSample.csproj, samples/SessionSample/Startup.cs, samples/SessionSample/appsettings.json
@Rick-Anderson I added this based on your suggestion before on #130, nothing but I comment the lines, because it's not needed unless someone want to you the SQL Server
=> Fix issue#130
